name: safe
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  flutter_secure_storage: ^6.0.0
  flutter_svg: ^1.1.5
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.19

flutter_native_splash:
  color: "#009BD3"
  image: assets/images/splash_screen.png
  android12:
    color: "#009BD3"
    # image: assets/images/splash_screen.png


flutter:
  uses-material-design: true
  assets:
    - assets/reward/
    - assets/images/
    - assets/category/
    - assets/pieces/
    - assets/svg/
    - assets/

  fonts:
    - family: UbuntuMono
      fonts:
        - asset: fonts/UbuntuMono-Regular.ttf
        - asset: fonts/UbuntuMono-Bold.ttf
          weight: 700

    - family: Averta
      fonts:
        - asset: fonts/AvertaBlack.otf
          weight: 900
        - asset: fonts/AvertaExtrabold.otf
          weight: 800
        - asset: fonts/AvertaBold.otf
          weight: 700
        - asset: fonts/AvertaSemibold.otf
          weight: 600
        - asset: fonts/AvertaRegular.otf
          weight: 400
        - asset: fonts/AvertaLight.otf
          weight: 300
        - asset: fonts/AvertaThin.otf
          weight: 200
        - asset: fonts/AvertaExtrathin.otf
          weight: 100